/*
|--------------------------------------------------------------------------
| SHOP2TOPUP ORDER CLIENT
|--------------------------------------------------------------------------
| The API that actually places a top-up:
|
|   POST /api/endpoints/v1/orders/create
|   GET  /api/endpoints/v1/orders/:orderId
|
| The wallet is charged the moment an order is created, so this client holds
| two rules:
|
|   1. The caller's order_id is never invented here. It is generated once by
|      the caller, stored on the order record, and reused for every later
|      attempt, because that UUID is the idempotency key: retrying with it
|      returns the order that already exists instead of charging again.
|   2. A transport failure is retried, not reported as a refusal. The order
|      may well have been created, and the only safe way to find out is to
|      ask again with the same order_id.
*/

const { randomUUID } = require("crypto");
const { request: defaultRequest, DEFAULT_BASE, DEFAULT_TIMEOUT } = require("./http");

const CREATE_PATH = "/api/endpoints/v1/orders/create";
const ORDER_PATH = "/api/endpoints/v1/orders/";

class Shop2TopupClient {
  constructor(config = {}) {
    this.baseUrl = config.baseUrl || process.env.SHOP2TOPUP_API_BASE || DEFAULT_BASE;
    this.apiKey = config.apiKey ?? process.env.SHOP2TOPUP_API_KEY ?? null;
    this.timeout = config.timeout || DEFAULT_TIMEOUT;
    this.orderTimeout = config.orderTimeout || 20000;

    // Three attempts, because the request is idempotent: a lost response is
    // free to repeat, a lost order is not.
    this.maxAttempts = config.maxAttempts ?? 3;
    this.retryDelayMs = config.retryDelayMs ?? 1500;

    // Injection points, so the tests can drive the whole adapter without a
    // network.
    this.request = config.request || defaultRequest;
    this.sleep =
      config.sleep || ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));

    this.requestCount = 0;
  }

  isConfigured() {
    return Boolean(this.apiKey);
  }

  /**
   * A new idempotency key. Generated by the caller-facing surface so it can
   * be stored on the order before anything is charged.
   */
  newOrderId() {
    return randomUUID();
  }

  /**
   * Place one order.
   *
   * `orderId` must already be persisted on the order record. The wallet is
   * charged by this call, so it is never generated as a side effect here.
   */
  async createOrder(request = {}) {
    const orderId = String(request.orderId || "").trim();

    if (!orderId) {
      throw new Error("A provider order_id is required before ordering");
    }

    const subCategoryId = Number(request.subCategoryId);

    if (!Number.isFinite(subCategoryId) || subCategoryId <= 0) {
      throw new Error(`Invalid sub_category_id: ${request.subCategoryId}`);
    }

    const body = {
      order_id: orderId,
      sub_category_id: subCategoryId,
      quantity: Number.isFinite(Number(request.quantity))
        ? Math.max(1, Math.trunc(Number(request.quantity)))
        : 1,
      requirements: { ...(request.requirements || {}) },
    };

    // Price protection is opt-in. Our prices are in LKR while the provider
    // charges in USD, so a value is only sent when the package configures
    // one that is genuinely the provider's currency.
    const expected = Number(request.expectedUnitPrice);

    if (request.expectedUnitPrice !== undefined && Number.isFinite(expected) && expected > 0) {
      body.expected_unit_price = String(expected);
    }

    return this.send("POST", CREATE_PATH, body);
  }

  /**
   * Read one order back. Used to resolve an order whose delivery was still
   * running when the shop lost track of it.
   */
  async getOrder(orderId) {
    const id = String(orderId || "").trim();

    if (!id) {
      throw new Error("A provider order_id is required for a status lookup");
    }

    return this.send("GET", ORDER_PATH + encodeURIComponent(id), null);
  }

  /**
   * One call, retried while the answer is safe to repeat.
   *
   * Every call this client makes is idempotent: the create call carries the
   * caller's order_id, and the lookup is a read. So a timeout, a dropped
   * socket or a 5xx is retried with the identical request rather than
   * reported as a refusal.
   */
  async send(method, path, body) {
    let lastError = null;

    for (let attempt = 1; attempt <= this.maxAttempts; attempt++) {
      this.requestCount++;

      let response;

      try {
        response = await this.request(method, path, {
          body,
          baseUrl: this.baseUrl,
          apiKey: this.apiKey,
          timeout: this.orderTimeout,
        });
      } catch (error) {
        lastError = error;

        if (attempt >= this.maxAttempts) {
          break;
        }

        console.warn(
          `[SHOP2TOPUP] ${method} ${path} attempt ${attempt} failed: ${
            error.message
          } - repeating the same request`
        );

        await this.sleep(this.retryDelayMs * attempt);
        continue;
      }

      // An empty answer is a transport failure like any other: the request
      // may have been charged, so it is repeated rather than believed.
      if (!response) {
        lastError = new Error("SHOP2TOPUP returned no response");

        if (attempt >= this.maxAttempts) {
          break;
        }

        await this.sleep(this.retryDelayMs * attempt);
        continue;
      }

      const statusCode = Number(response?.statusCode) || 0;

      if (
        (statusCode === 429 || statusCode >= 500) &&
        attempt < this.maxAttempts
      ) {
        lastError = Object.assign(
          new Error(`SHOP2TOPUP responded ${statusCode}`),
          { statusCode }
        );

        console.warn(
          `[SHOP2TOPUP] ${method} ${path} attempt ${attempt} answered ${statusCode} - repeating the same request`
        );

        await this.sleep(
          this.backoffMs(response, this.retryDelayMs * attempt)
        );
        continue;
      }

      return response;
    }

    const error = new Error(
      `SHOP2TOPUP ${method} ${path} did not answer: ${
        lastError?.message || "no response"
      }`
    );

    error.code = lastError?.code || "PROVIDER_UNREACHABLE";
    error.retryable = true;
    error.lastResponse = lastError?.lastResponse ?? null;

    throw error;
  }

  /**
   * Honour Retry-After when the provider sends one, so a rate limit is
   * waited out rather than hammered. The cap stops a hostile header from
   * parking fulfilment for minutes.
   */
  backoffMs(response, fallbackMs) {
    const header = response?.headers?.["retry-after"];
    const seconds = Number(header);

    if (Number.isFinite(seconds) && seconds > 0) {
      return Math.min(seconds * 1000, 30000);
    }

    return fallbackMs;
  }
}

module.exports = {
  Shop2TopupClient,
  CREATE_PATH,
  ORDER_PATH,
};